[project]
name = "data-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "akshare>=1.19.1",
    "ccxt>=4.5.84",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.2",
    "mplfinance>=0.12.10b0",
    "pandas>=3.0.6",
    "requests>=2.34.2",
    "seaborn>=0.13.2",
    "yfinance>=1.7.0",
]
